### ISSUE TITLE
Backup Option

### ISSUE THREAD

**Issue by balakumarane** [Spikeysanju/Expenso#101]
Is there any backup option available ?

**Comment by Pranab009** [comment]
Please add backup options

**Comment by Spikeysanju** [comment]
@balakumarane AFAIK no. Initially I thought of adding a `backup option` with `export to CSV file`. But I promise you that in upcoming weeks this app will be fully migrated to `Jetpack Compose` with some `new interesting features` in it.

Compose migration & New features details here - [Expenso New Features](https://github.com/Spikeysanju/Expenso/issues/146)


Keep an eye on this repo by clicking `watch` on top right corner.

**Comment by Spikeysanju** [comment]
@balakumarane Backup option is recently added with the latest PR #169. Please check it out & feel free ask any questions. Thank you!

Closing this issue for now 👍
