### ISSUE TITLE
Refactoring TransactionViewModel

### ISSUE THREAD

**Issue by yash-k9** [Spikeysanju/Expenso#214]
**Is your feature request related to a problem? Please describe.**
`TransactionViewModel` is extending **AndroidViewModel** which takes in application context and requires a _viewmodelFactory_ to be initialized. In the viewmodel, I observed that only UiModeDataStore is using the application context which can be directly injected by Hilt

**Describe the solution you'd like**
Instead of using the **AndroidViewModel**, we can extend to **ViewModel** and Inject the UiModeDataStore directly through constructor. This will also eliminate the use of the _viewmodelFactory_

**Describe alternatives you've considered**
I've refactored the code and the behaviour is as expected. I can raise a PR if this change is approved.

**Comment by Spikeysanju** [comment]
@yash-k9 Thanks for bringing this up. Yes I agreed with your statement. Feel free to create a PR for this 👍 .
