### ISSUE TITLE
Downgrade to Stable

### ISSUE THREAD

**Issue by maifeeulasad** [Spikeysanju/Expenso#50]
This awesome project uses many beta libraries, is there any specific reason behind this ? Please let us know. 

And if the answer is no, I've tried to fix this problem, here : https://github.com/maifeeulasad/Expenso/commit/598d24a257b80ac74a15b4f406bfa90c585d0745

**Comment by Spikeysanju** [comment]
Hey buddy @maifeeulasad , thanks for your contribution. Yes this project uses many beta libraries & I made this as an intentional 👍
